server:
  port:8080
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
     connectionTimeout: 20000
     maximumPoolSize: 5



