server:
  port:8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: mySql@#110
    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always


